CREATE DATABASE IF NOT EXISTS citiesAPI_DB;

USE citiesAPI_DB;

CREATE TABLE city (
	zip VARCHAR(5) NOT NULL,
	name VARCHAR(40) NOT NULL,
	province VARCHAR(2) NOT NULL,
	altitude NUMERIC NOT NULL,
	CONSTRAINT citiPK PRIMARY KEY (zip,name)
);

